### ISSUE TITLE
[US07] Excluir Produtos

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [UnBArqDsw2020-2/2020.2_G5_EasyCoffee_Backend#10]
**Descrição da História de Usuário**
Eu, como administrador, quero excluir produtos no site.

**Feature**
Manter Produto

**Tasks**
- [ ] Criação de botão de excluir produto na página de "visualizar-produto-administrador".
- [ ] O sistema deve ser capaz de excluir um produto.
- [ ] Antes do produto ser excluído, deve ser apresentado uma mensagem de confirmação.
- [ ] Quando o sistema excluir um produto, deve ser apresentado a mensagem "Produto excluído com sucesso.".

**Critérios de Aceitação**
- [ ] O administrador do sistema deve ser capaz de excluir um produto.
- [ ] O administrador deve estar logado para excluir um produto.
- [ ] Deve existir uma mensagem de confirmação, antes de um produto ser excluído.
- [ ] Depois de excluir um produto , ele deve desaparecer para compra.
