### ISSUE TITLE
[US08] Visualizar Produtos Cadastrados

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [UnBArqDsw2020-2/2020.2_G5_EasyCoffee_Backend#11]
**Descrição da História de Usuário**
Eu, como administrador, quero visualizar os produtos cadastrados.

**Feature**
Manter Produto

**Tasks**
- [ ] Criação de página "visualizar-produto-administrador".

**Critérios de Aceitação**
- [ ] O administrador do sistema deve ser capaz de visualizar os produtos cadastrados.
- [ ] O administrador deve estar logado para acessar essa página.
- [ ] Essa página deverá conter a opção de editar, excluir e colocar um produto em promoção (botões).
