### ISSUE TITLE
[US09] Avaliar Produto

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [UnBArqDsw2020-2/2020.2_G5_EasyCoffee_Backend#12]
**Descrição da História de Usuário**
Eu, como cliente, quero avaliar um produto comprado.

**Feature**
Avaliação

**Tasks**
- [ ] Criação da página "avaliar-compra".
- [ ] O sistema de ser capaz de salvar a avaliação feita.
- [ ] Quando o sistema salvar a avaliação de ser apresentado a mensagem "Avaliação feita com sucesso."

**Critérios de Aceitação**
- [ ] O cliente do sistema deve ser capaz de avaliar produtos.
- [ ] O cliente deve estar logado para avaliar o produto.
- [ ] Depois de avaliar o produto deve ser possível ver a avaliação.
