### ISSUE TITLE
[US12] Adicionar Produto no Carrinho

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [UnBArqDsw2020-2/2020.2_G5_EasyCoffee_Backend#15]
**Descrição da História de Usuário**
Eu, como cliente, quero adicionar produtos no carrinho de compras.

**Feature**
Carrinho de Compras

**Tasks**
- [ ] Na tela de "comprar-produto" deve ser capaz de adicionar o produto no carrinho como está no protótipo.
- [ ] O usuário deve ser capaz de adicionar o produto ao carrinho.

**Critérios de Aceitação**
- [ ] O cliente de ser capaz de adicionar o produto no carrinho com a quantidade informada.
- [ ] O cliente deve estar logado no sistema.
