### ISSUE TITLE
[US13] Excluir Produtos do Carrinho

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [UnBArqDsw2020-2/2020.2_G5_EasyCoffee_Backend#16]
**Descrição da História de Usuário**
Eu, como cliente, quero excluir produtos do carrinho de compras.

**Feature**
Carrinho de Compras

**Tasks**
- [ ] A tela de "carrinho" deve ser desenvolvido como está no protótipo.
- [ ] O usuário deve ser capaz de excluir o produto do carrinho.

**Critérios de Aceitação**
- [ ] O cliente de ser capaz de excluir o produto no carrinho.
- [ ] O cliente deve estar logado no sistema.
