### ISSUE TITLE
[US14] Editar Carrinho

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [UnBArqDsw2020-2/2020.2_G5_EasyCoffee_Backend#17]
**Descrição da História de Usuário**
Eu, como cliente, quero editar a quantidade de um determinado produto no carrinho de compras.

**Feature**
Carrinho de Compras

**Tasks**
- [ ] O cliente deve ser capaz de alterar a quantidade de produtos no carrinho.
- [ ] A tela de edição deve ser feita como planejado no protótipo.

**Critérios de Aceitação**
- [ ] O cliente deve ser capaz de aditar seu carrinho.
- [ ] O cliente deve estar logado no sistema.
