### ISSUE TITLE
[US15] Compra

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [UnBArqDsw2020-2/2020.2_G5_EasyCoffee_Backend#18]
**Descrição da História de Usuário**
Eu, como cliente, quero realizar compra de produtos.

**Feature**
Carrinho de Compras

**Tasks**
- [ ] O cliente deve ser capaz de selecionar os produtos e adicionar ao carrinho.
- [ ] A tela onde os produtos estão listados deve ser feita em conformidade com o protótipo.

**Critérios de Aceitação**
- [ ] O cliente pode adicionar corretamente seus produtos ao carrinho.
- [ ] O cliente deve estar logado em sua conta.
