### ISSUE TITLE
[US16] Cadastrar Frete

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [UnBArqDsw2020-2/2020.2_G5_EasyCoffee_Backend#19]
**Descrição da História de Usuário**
Eu, como administrador, quero cadastrar informações a respeito do frete.

**Feature**
Carrinho de Compras

**Tasks**
- [ ] O administrador do sistema deve ser capaz de cadastrar informações sobre o preço do frete.
- [ ] A tela onde o frete é cadastrado deve ser feita em conformidade com o protótipo.

**Critérios de Aceitação**
- [ ] O administrador pode adicionar corretamente as informações sobre o frete dos produtos.
- [ ] Apenas o administrador logado em sua conta pode cadastrar informações sobre o frete.
