### ISSUE TITLE
[US17] Visualizar Frete

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [UnBArqDsw2020-2/2020.2_G5_EasyCoffee_Backend#20]
**Descrição da História de Usuário**
Eu, como cliente, quero visualizar informações a respeito do frete.

**Feature**
Carrinho de Compras

**Tasks**
- [ ] O cliente deve ser capaz de visualizar informações sobre o frete de seus produtos.
- [ ] A tela onde o frete é mostrado deve ser feita em conformidade com o protótipo.

**Critérios de Aceitação**
- [ ] O cliente deve ver as informações sobre o frete apenas de seus produtos.
- [ ] O cliente logado em sua conta para visualizar informações sobre o frete.
