### ISSUE TITLE
[US01] Visualizar Produtos

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [UnBArqDsw2020-2/2020.2_G5_EasyCoffee_Backend#3]
**Descrição da História de Usuário**
Eu, como cliente, quero visualizar os produtos do site, para saber o que está disponível para compra.

**Feature**
Listar

**Tasks**
- [ ] Criação da página "comprar-cafe" de acordo com o protótipo.
- [ ] O sistema de ser capaz de trazer os produtos disponibilizados pelo administrador do sistema contendo o nome do produto e seu valor.
Critérios de aceitação:

**Critérios de Aceitação**
- [ ] O cliente deve ser capaz de navegar com facilidade pelos produtos.
- [ ] O cliente deve ser capaz de visualizar todos os produtos disponíveis para compra.
- [ ] O site deve ser responsivo para facilitar a navegação em diferentes aparelhos.
