### ISSUE TITLE
[US02] Visualizar um Produto

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [UnBArqDsw2020-2/2020.2_G5_EasyCoffee_Backend#5]
**Descrição da História de Usuário**
Eu, como cliente, quero visualizar as informações sobre um determinado produto.

**Feature**
Listar

**Tasks**
- [ ] O sistema deve ser capaz de trazer as informações do produto de acordo com a página "comprar-cafe" de acordo com o protótipo.
- [ ]O sistema deve trazer as informações correspondentes do produto quando o usuário clicar sobre ele.

**Critérios de Aceitação**
- [ ] O cliente deve ser capaz de visualizar as informações do produto.
