### ISSUE TITLE
[US03] Visualizar Produto por Categoria

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [UnBArqDsw2020-2/2020.2_G5_EasyCoffee_Backend#6]
**Descrição da História de Usuário**
Eu, como cliente, quero vizualizar os produtos por categorias.

**Feature**
Listar

**Tasks**
- [ ] Criação da página "menus" de acordo com o protótipo.
- [ ] O sistema de ser capaz de separar os produtos por categorias.

**Critérios de Aceitação**
- [ ] O cliente deve ser capaz de navegar com facilidade pelas categorias.
- [ ] O cliente deve ser capaz de visualizar todos os produtos disponíveis para compra de acordo com as suas categorias.
- [ ] O site deve ser responsivo para facilitar a navegação em diferentes aparelhos.
