### ISSUE TITLE
[US04] Cadastrar Produtos

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [UnBArqDsw2020-2/2020.2_G5_EasyCoffee_Backend#7]
**Descrição da História de Usuário**
Eu, como administrador, quero cadastrar produtos no site.

**Feature**
Manter Produto

**Tasks**
- [ ] Criação da página "cadastrar-produto".
- [ ] O sistema de ser capaz de salvar os produtos criados.
- [ ] Quando o sistema salvar o produto deve ser apresentado a mensagem "Produto cadastrado com sucesso.".

**Critérios de Aceitação**
- [ ] O administrador do sistema deve ser capaz de cadastrar produtos.
- [ ] O administrador deve estar logado para cadastrar o produto.
- [ ] Depois de cadastrar o produto, ele deve ser disponibilizado para compra.
