### ISSUE TITLE
[US05] Editar Produtos

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [UnBArqDsw2020-2/2020.2_G5_EasyCoffee_Backend#8]
**Descrição da História de Usuário**
Eu, como administrador, quero editar produtos no site.

**Feature**
Manter Produto

**Tasks**
- [ ] Criação da página "editar-produto".
- [ ] O sistema deve ser capaz de editar as informações de produtos cadastrados no site.
- [ ] Antes das alterações serem salvas, deve ser apresentado uma mensagem de confirmação.
- [ ] Quando o sistema salvar as alterações do produto deve ser apresentado a mensagem "Produto editado com sucesso.".

**Critérios de Aceitação**
- [ ] O administrador do sistema deve ser capaz de editar produtos.
- [ ] O administrador deve estar logado para editar um produto.
- [ ] Antes do produto ter a alteração salva, deve ser apresentado uma mensagem de confirmação.
- [ ] Depois de editar um produto, ele deve ter suas informações atualizadas para compra.
