### ISSUE TITLE
[US06] Colocar Produto em Promoção

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [UnBArqDsw2020-2/2020.2_G5_EasyCoffee_Backend#9]
**Descrição da História de Usuário**
Eu, como administrador, quero colocar um produto em promoção.

**Feature**
Manter Produto

**Tasks**
- [ ] Criação de opção de colocar um produto em promoção na página "visualizar-produto-administrador".
- [ ] Criação de página "colocar-produto-em-promoçao".
- [ ] O sistema deve ser capaz de colocar um produto em promoção.
- [ ] Antes das alterações serem salvas, deve ser apresentado uma mensagem de confirmação.
- [ ] Quando o sistema colocar o produto em promoção, deve ser apresentado a mensagem "Produto colocado em promoção com sucesso.".

**Critérios de Aceitação**
- [ ] O administrador do sistema deve ser capaz de colocar um produto em promoção.
- [ ] O administrador deve estar logado para colocar um produto em promoção.
- [ ] Antes do produto ter a alteração salva, deve ser apresentado uma mensagem de confirmação.
- [ ] Depois de colocar um produto em promoção, ele deve ter suas informações atualizadas para compra.
